# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
      branches: ["main"]
  pull_request:
      branches: ["main", "dev"]

jobs:
  build:
      name: Backend test
      runs-on: ubuntu-latest
  
      defaults:
        run:
            working-directory: ./quirknotes/backend
    
      strategy:
        matrix:
            node-version: [20.x]
            mongodb-version: ['latest']
  
      steps:
      - uses: actions/checkout@v3
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Initialize MongoDB'
        uses: MongoCamp/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      
      - run: mkdir data
      - run: mkdir data/db
      - run: npm i mongod
      - run: mongod --dbpath=./data/db
      - run: npm run dev
      - run: npm i
      - run: npm test

